version: "3.9"
services: 
  backend:
    # build: ./homebrewapi-image/
    image: "homebrewapi-image"
    container_name: homebrewapi-nginx
    ports:
      - "59607:59607"
  frontend:
    image: nginx:alpine
    volumes:
      # - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4004:80"
